version: '3'

services:
  postgres:
    image: postgres:15
    container_name: blogai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogai_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blogai-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogai-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/blogai_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret
      - OPENAI_API_KEY=your-openai-api-key
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - blogai-network

networks:
  blogai-network:
    driver: bridge

volumes:
  postgres-data: